FROM ubuntu:18.04
RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && apt-get install -y --reinstall systemd \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

RUN apt-get update && apt-get install -y vim supervisor nginx net-tools curl cron
RUN pip install gunicorn django requests
RUN apt-get install nginx vim

# Nginx service setting file
ADD  /static/async.conf /etc/nginx/sites-enabled/
COPY  /static/nginx.conf /etc/nginx/nginx.conf


# Default nginx setting 을 지워주어야 한다.
RUN rm -f /etc/nginx/sites-available/default
RUN rm -f /etc/nginx/sites-enabled/default

# Entrypoint
EXPOSE 80
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]


# docker run -d --rm -p 80:80 nginx
# /Users/publicai/PycharmProjects/django-tutorial/asynch/asynch_tutorial/nginx
